### PR TITLE
11035 - Fix scope issue to allow printing of report

### LINKED ISSUE #11035: Printing report from Resource Editor causes error
When a user is in the Resource Manager and selects Print Report from the top left dropdown menu, an error is returned in the console.

image

### PR DESCRIPTION
**Pull request by csmith-he**
### Types of changes

-   [X] Bugfix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Description of Change

There was an issue with the scope to allow the print to occur when triggers from the Resource Manager; the scope has been changed to allow the print.

### Issues Solved
closes #11035 

### Checklist

-   I targeted one of these branches:
    - [ ] dev/7.6.x (under development): features, bugfixes not covered below
    - [X] dev/7.5.x (main support): regressions, crashing bugs, security issues, major bugs in new features
    - [ ] dev/6.2.x (extended support): major security issues, data loss issues
-   [ ] I added a changelog in arches/releases
-   [ ] I submitted a PR to arches-docs (if appropriate)
-   [ ] Unit tests pass locally with my changes
-   [ ] I added tests that prove my fix is effective or that my feature works
-   [ ] My test fails on the target branch

#### Ticket Background
*   Sponsored by: Historic England
*   Found by: @csmith-he 
*   Tested by: @csmith-he 

### Further comments

This fix will be needed for Arches for HERs release

### CODE REVIEW

File: arches/app/media/js/views/resource/report.js [hunk 1]
```diff
@@ -10,7 +10,8 @@ require([
             BaseManagerView.prototype.initialize.call(this, options);
             
             if (location.search.indexOf('print') > 0) {
-                this.viewModel.loading(true);
+                var self = this
```
Comment (chiatt) [inline arches/app/media/js/views/resource/report.js:13]: Could you change `var` to `const` and add a semicolon?

Comment (csmith-he) [reply arches/app/media/js/views/resource/report.js]: Request change made - thanks for flagging that up!

**Review by chiatt — APPROVED** [review]
Looks good!
