### PR TITLE
Fix term-filter.clear method #11443

### LINKED ISSUE #11443: term-filter.clear() clears selectWoo dom elements of tags but not terms unless new ajax query
When a search-filter gets cleared, the UI should also reflect that. In a search-view that doesn't make a new ajax request when the query changes back to the default (no search parameters), the selectWoo elements part of the term-filter persist even though the underlying `tags` and `terms` have already been removed thus (from `views/components/search/term-filter.js`):
```.js
clear: function() {
            this.filter.terms.removeAll();
            this.filter.tags.removeAll();
        }
```

See video below for example:

https://github.com/user-attachments/assets/5dc07ace-0385-4689-846d-9e415430aa53

### PR DESCRIPTION
**Pull request by whatisgalen**
### Types of changes

-   [x] Bugfix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Description of Change

When the `term-filter` is used to include search terms, the ko.observableArray `terms` gets a new `term` object but the ko.observableArray `tags` does not. The logic in the term-search binding only updates the selectWoo UI when `tags` gets updated, not `terms` (unless a user individually clicks "x" on the term, or the ensuing query updates the term-filter state). This PR adds a subscription to `terms` to update (empty) the selectWoo if there are neither tags nor terms.

### Issues Solved

Closes #11443 

### Checklist

-   I targeted one of these branches:
    - [x] dev/7.6.x (under development): features, bugfixes not covered below
    - [ ] dev/7.5.x (main support): regressions, crashing bugs, security issues, major bugs in new features
    - [ ] dev/6.2.x (extended support): major security issues, data loss issues
-   [ ] I added a changelog in arches/releases
-   [ ] I submitted a PR to arches-docs (if appropriate)
-   [ ] Unit tests pass locally with my changes
-   [ ] I added tests that prove my fix is effective or that my feature works
-   [ ] My test fails on the target branch

#### Accessibility Checklist

[Developer Guide](https://arches.readthedocs.io/en/stable/developing/advanced/accessibility/)

| Topic            | Changed | Retested |
| ---------------- | ------- | -------- |
| Color contrast   |         |          |
| Form fields      |         |          |
| Headings         |         |          |
| Links            |         |          |
| Keyboard         |         |          |
| Responsive Design|         |          |
| HTML validation  |         |          |
| Screen reader    |         |          |

#### Ticket Background
*   Sponsored by: 
*   Found by: @ 
*   Tested by: @ 
*   Designed by: @

### CODE REVIEW

File: arches/app/media/js/bindings/term-search.js [hunk 1]
```diff
@@ -28,6 +28,10 @@ define([
                 }); 
                 searchbox.trigger('change');
             });
```
Comment (apeters) [inline arches/app/media/js/bindings/term-search.js:30]: If you add both a resource-type filter along with a term-filter and hit the clear button you'll notice that you'll need this logic here too:

```suggestion
                if (terms.length == 0 && searchbox.tags.length == 0){
                    searchbox.empty();
                }
```

**Review by apeters — CHANGES_REQUESTED** [review]

File: arches/app/media/js/bindings/term-search.js (hunk 1 above)
Comment (whatisgalen) [reply arches/app/media/js/bindings/term-search.js:30]: I'm assuming this committed change was limited to line 29 as otherwise the deleted `});` breaks things

**Review by apeters — APPROVED** [review]
looks good
