### PR TITLE
Fix language selection in text widgets #10122

### LINKED ISSUE #10122: Both text widgets throw TypeErrors when using language selector
In the (text or Rich Text widgets), select a language from the picker.

Result:
```js
rich-text.js:81 Uncaught TypeError: Cannot set properties of undefined (setting 'value')
    at a.gc.eval [as kc] (rich-text.js:81:48)
    at Function.notifySubscribers (knockout-latest.js:42:453)
    at Function.wa (knockout-latest.js:47:255)
    at viewModel.c [as currentText] (knockout-latest.js:46:494)
    at a.gc.eval [as kc] (rich-text.js:106:12)
    at Function.notifySubscribers (knockout-latest.js:42:453)
    at Function.wa (knockout-latest.js:47:255)
    at c (knockout-latest.js:46:494)
    at Object.$a (knockout-latest.js:71:237)
    at HTMLSelectElement.k (knockout-latest.js:118:478)
```

Repeat. Second error is slightly different:

```js
rich-text.js:93 Uncaught TypeError: Cannot set properties of undefined (setting 'direction')
    at a.gc.eval [as kc] (rich-text.js:93:52)
    at Function.notifySubscribers (knockout-latest.js:42:453)
    at Function.wa (knockout-latest.js:47:255)
    at viewModel.c [as currentDirection] (knockout-latest.js:46:494)
    at a.gc.eval [as kc] (rich-text.js:107:12)
    at Function.notifySubscribers (knockout-latest.js:42:453)
    at Function.wa (knockout-latest.js:47:255)
    at c (knockout-latest.js:46:494)
    at Object.$a (knockout-latest.js:71:237)
    at HTMLSelectElement.k (knockout-latest.js:118:478)
```

Version: 7.5.dev @ 76670b00df05cea8525423548592497e7406f68a

### PR DESCRIPTION
**Pull request by jacobtylerwalls**
### Types of changes

-   [x] Bugfix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Description of Change
Before, using the language picker in the text/rich text widgets would not actually save language/direction to the tile, as only the key in the I18n object was the language before changing (likely to be English).

### Issues Solved

Closes #10122

### Checklist

-   [ ] Unit tests pass locally with my changes
-   [ ] I have added tests that prove my fix is effective or that my feature works
-   [ ] I have added necessary documentation (if appropriate)

#### Ticket Background
*   Sponsored by: 
*   Found by: @ 
*   Tested by: @ 
*   Designed by: @ 

### Testing instructions
- [ ] Text widget
  - Manipulate language, direction, save
  - Check tile data
- [ ] Repeat with rich text widget

### Further comments
LMK if I should target 7.4.x instead.

### CODE REVIEW

File: arches/app/media/js/views/components/widgets/rich-text.js [hunk 1]
```diff
@@ -80,6 +80,9 @@ define([
             const currentLanguage = self.currentLanguage();
             if(!currentLanguage) { return; }
 
+            if(!currentValue?.[currentLanguage.code]){
+                currentValue[currentLanguage.code] = {};
+            }
```
Comment (jacobtylerwalls) [inline arches/app/media/js/views/components/widgets/rich-text.js:85]: Copied from the code in text.js that already had this for direction switches.

**Review by chrabyrd — APPROVED** [review]
lgtm!
