### PR TITLE
Fix file-list max files enforcement

### LINKED ISSUE #12542: File List datatype `activateMax` field not configurable
In the graph designer, interaction with the `activateMax` config option is unimplemented when configuring a new file list node. This means that even if a graph designer limits the number of files that can be saved for that node, the validation check [here](https://github.com/archesproject/arches/blob/28c74cb54fe9396f944c6cf19a2313d8724954a4/arches/app/datatypes/datatypes.py#L1179) will not be enforced. Since this param has not been implemented and I think most graph designers would just expect that supplying a max file count would enforce that limit, we should swap that part of the conditional for a check of truthy `maxFiles`.

### PR DESCRIPTION
**Pull request by johnatawnclementawn**
### Types of changes

-   [x] Bugfix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Description of Change

There was an unimplemented flag that was needed to enforce the maximum file number limit. This removes that flag and makes the enforcement of max files more intuitive.

### Issues Solved

Closes #12542

### Checklist

-   I targeted one of these branches:
    - [x] dev/8.1.x (under development): features, bugfixes not covered below
    - [ ] dev/8.0.x (main support): regressions, crashing bugs, security issues, major bugs in new features
    - [ ] dev/7.6.x (extended support): major security issues, data loss issues
-   [x] I added a changelog in arches/releases
-   [ ] I submitted a PR to arches-docs (if appropriate)
-   [x] Unit tests pass locally with my changes
-   [ ] I added tests that prove my fix is effective or that my feature works
-   [ ] My test fails on the target branch

#### Accessibility Checklist

[Developer Guide](https://arches.readthedocs.io/en/stable/developing/advanced/accessibility/)

| Topic            | Changed | Retested |
| ---------------- | ------- | -------- |
| Color contrast   |         |          |
| Form fields      |         |          |
| Headings         |         |          |
| Links            |         |          |
| Keyboard         |         |          |
| Responsive Design|         |          |
| HTML validation  |         |          |
| Screen reader    |         |          |

#### Ticket Background
*   Sponsored by: GCI 
*   Found by: @johnatawnclementawn  
*   Tested by: @ 
*   Designed by: @johnatawnclementawn

### CODE REVIEW

File: arches/app/media/js/views/components/datatypes/file-list.js [hunk 1]
```diff
@@ -25,16 +25,34 @@ const viewModel = function(params) {
...
+                params.config.maxFiles(int);
+            } else {
+                self.maxFiles(
+                    params.config.maxFiles() == null ? "" :
+                    params.config.maxFiles().toString()
+                );
+            }
+        });
+        params.config.maxFiles.subscribe(function(val) {
+            var stringified_val = (val === null ? "" : val.toString());
```
Comment (chrabyrd) [inline arches/app/media/js/views/components/datatypes/file-list.js]: snake_case in JS? `var` declarations? 😅

File: arches/app/media/js/views/components/datatypes/file-list.js [hunk 2]
```diff
@@ -25,16 +25,34 @@ const viewModel = function(params) {
...
+                return;
+            }
+
             var int = parseInt(val);
-            if(int > 0) { params.config.maxFiles(int); }
-            else { self.maxFiles(1); }
+            if(!isNaN(int) && int > 0) { 
+                params.config.maxFiles(int);
+            } else {
+                self.maxFiles(
```
Comment (chrabyrd) [inline arches/app/media/js/views/components/datatypes/file-list.js]: nit: no multi-line ternaries

**Review by chrabyrd — CHANGES_REQUESTED** [review]
looks good! just some minor nits

File: arches/app/media/js/views/components/datatypes/file-list.js (hunk 1 above)
Comment (johnatawnclementawn) [reply arches/app/media/js/views/components/datatypes/file-list.js]: That's on me... snake_case cause I forgot where I was in the stack 😅  and var cause I didn't clean up after copilot. Sorry about that 🤦

**Comment by johnatawnclementawn** [comment]
~~@chrabyrd is it too heavy-handed to add logic to the migration to remove `activateMax` from any existing file-list nodes in a user's graphs? I feel like the answer is no, but I just want to be sure~~
Added in latest

**Review by chrabyrd — APPROVED** [review]
LGTM!
